### ISSUE TITLE
Deployment on static host

### ISSUE THREAD

**Issue by jawadan** [vuestorefront-community/woocommerce#13]
### What is your question / Please describe your issue

Is there any possibility to deploy VSF2 on Netlify?

### What version of woocommerce are you using?

5.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
For anyone looking at this in the future. No, deployment on Netlify is not possible because it supports only the static deployment while VSF is Server Side Rendered
